import type { Metadata } from "next";
import "./globals.css";
import Logo from "./components/Logo";
import Header from "./components/Header";
import { PostsProvider } from "./contexts/PostsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white-default bg-black-default font-light min-h-screen">
        <main className="flex flex-col justify-between items-center min-h-screen">
            <Header/>
            <PostsProvider>
              <div className="py-8 px-6 mb-auto w-full">
                {children}
              </div>
            </PostsProvider>
            <footer className="w-full bg-black-light flex flex-col gap-4 justify-center items-center py-4 px-10">
                <Logo/>
                <p className="text-sm">Inspirado en el proyecto de <a className="text-main" href="https://moure.dev" target="_blank">@mouredev</a></p>
            </footer>
        </main>
      </body>
    </html>
  );
}
